version = 1
notes_root = "docs/log"
template_root = ".projio/notio/templates"

[types.idea]
mode = "event"
template = "idea.md"
filename = "idea-{owner}-{timestamp}.md"
toc_keys = ["title", "series"]

[types.issue]
mode = "event"
template = "issue.md"
filename = "issue-{owner}-{timestamp}.md"
toc_keys = ["status"]
toc_groupby = "status"

[types.task]
mode = "event"
template = "task.md"
filename = "task-{owner}-{timestamp}.md"
toc_keys = ["status", "title"]
toc_groupby = "status"

[types.meeting]
mode = "event"
template = "meeting.md"
filename = "meeting-{owner}-{timestamp}.md"
toc_keys = ["participants"]

# [diataxis]
# docs_root = "docs"
# sections = ["tutorials", "how-to", "explanation", "reference"]
